alter table PETCLINIC_INVOICE add constraint FK_PETCLINIC_INVOICE_DOCUMENT foreign key (DOCUMENT_ID) references SYS_FILE(ID);
create index IDX_PETCLINIC_INVOICE_DOCUMENT on PETCLINIC_INVOICE (DOCUMENT_ID);
